### ISSUE TITLE
installing pynio alon newest netCDF4 version

### ISSUE THREAD

**Issue by mathause** [conda-forge/pynio-feedstock#90]
Issue: 

pynio can not be installed alongside the newest version of `netCDF4` (is this right place to report this?). To reproduce:

```bash
conda install netcdf4=1.5.4 pynio
```
This may be because of the required hdf5 version (although other dependencies may also conflict):

  - pynio: `hdf5 >=1.10.5,<1.10.6.0a0`
  - netCDF4: `hdf5 >=1.10.6,<1.10.7.0a0`

Excerpt from `conda search --info pynio`:
```yaml
pynio 1.5.5 py38h71ad7bc_11
---------------------------
file name   : pynio-1.5.5-py38h71ad7bc_11.tar.bz2
name        : pynio
version     : 1.5.5
build       : py38h71ad7bc_11
build number: 11
size        : 5.6 MB
license     : BSD 3-clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pynio-1.5.5-py38h71ad7bc_11.tar.bz2
md5         : 8612a1fa55d5a3c76fd01fdecd888799
timestamp   : 2020-03-31 12:47:00 UTC
dependencies: 
  - g2clib 1.6.0.*
  - hdf4 >=4.2.13,<4.3.0a0
  - hdf5 >=1.10.5,<1.10.6.0a0
  - hdfeos2
  - hdfeos5
  - jasper >=1.900.1,<2.0a0
  - libgcc-ng >=7.3.0
  - libgdal >=3.0.4,<3.1.0a0
  - libgfortran-ng >=7,<8.0a0
  - libnetcdf >=4.7.4,<4.7.5.0a0
  - libstdcxx-ng >=7.3.0
  - numpy >=1.14.6,<2.0a0
  - proj >=6.3.1,<6.3.2.0a0
  - python >=3.8,<3.9.0a0
  - python_abi 3.8.* *_cp38
```
Excerpt from `conda search --info netCDF4`
```yaml
netcdf4 1.5.4 nompi_py38hec8b9af_102
------------------------------------
file name   : netcdf4-1.5.4-nompi_py38hec8b9af_102.tar.bz2
name        : netcdf4
version     : 1.5.4
build       : nompi_py38hec8b9af_102
build number: 102
size        : 503 KB
license     : OSI Approved and MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/netcdf4-1.5.4-nompi_py38hec8b9af_102.tar.bz2
md5         : 475bf6605b0dd462a09c4444eb31d096
timestamp   : 2020-08-23 19:41:38 UTC
dependencies: 
  - cftime
  - hdf5 >=1.10.6,<1.10.7.0a0
  - libgcc-ng >=7.5.0
  - libnetcdf >=4.7.4,<4.7.5.0a0
  - libssh2 >=1.8.2,<2.0a0
  - numpy >=1.16.5,<2.0a0
  - python >=3.8,<3.9.0a0
  - python_abi 3.8.* *_cp38
  - setuptools
```

<br/>

Output from `conda install netcdf4=1.5.4 pynio`

<details>

```
(base) mathause@poisson:~$ conda install netcdf4=1.5.4 pynio
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package hdf5 conflicts for:
pynio -> hdfeos5 -> hdf5[version='*|*|*|1.8.15.*|1.8.17.*|1.8.17|1.8.17.*|1.8.18|1.8.18.*|>=1.10.3,<1.10.4.0a0|>=1.10.6,<1.10.7.0a0|>=1.10.6,<1.10.7.0a0|>=1.10.6,<1.10.7.0a0|>=1.10.5,<1.10.6.0a0|>=1.10.5,<1.10.6.0a0|>=1.10.1,<1.10.2.0a0|1.10.2.*|>=1.8.20,<1.9.0a0',build='mpi_openmpi_*|mpi_openmpi_*|mpi_openmpi_*|nompi_*|mpi_mpich_*|mpi_mpich_*|mpi_mpich_*']
pynio -> hdf5[version='1.10.1|>=1.10.2,<1.10.3.0a0|>=1.10.4,<1.10.5.0a0|>=1.10.5,<1.10.6.0a0|1.8.15.1|>=1.8.18,<1.8.19.0a0']

Package ca-certificates conflicts for:
python=3.8 -> openssl[version='>=1.1.1h,<1.1.2a'] -> ca-certificates
pynio -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

Package hdf4 conflicts for:
pynio -> hdfeos2 -> hdf4=4.2
pynio -> hdf4[version='>=4.2.13,<4.2.14.0a0|>=4.2.13,<4.3.0a0']

Package jpeg conflicts for:
pynio -> jpeg
pynio -> hdf4[version='>=4.2.13,<4.3.0a0'] -> jpeg[version='9.*|>=9c,<10a|>=9b,<10a|9b|>=9d,<10a']

Package python_abi conflicts for:
pynio -> numpy[version='>=1.14.6,<2.0a0'] -> python_abi[version='2.7.*|3.6',build='*_pypy36_pp73|*_cp27mu']
pynio -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp37m|*_cp36m|*_cp38']

Package krb5 conflicts for:
pynio -> krb5
pynio -> curl -> krb5[version='1.14.*|>=1.14.6,<1.15.0a0|>=1.16.1,<1.17.0a0|>=1.16.2,<1.17.0a0|>=1.16.3,<1.17.0a0|>=1.16.4,<1.17.0a0|>=1.17.1,<1.18.0a0|>=1.18.2,<1.19.0a0']

Package numpy-base conflicts for:
pynio -> numpy[version='>=1.14.6,<2.0a0'] -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.17.0|1.17.0|1.17.0|1.17.0|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|>=1.9.3,<2.0a0',build='py37hdbf6ddf_6|py27hdbf6ddf_6|py36hdbf6ddf_6|py27h2b20989_7|py35hdbf6ddf_7|py37hdbf6ddf_7|py37h2b20989_7|py37h2b20989_7|py36h2b20989_7|py37hdbf6ddf_7|py36hdbf6ddf_8|py27hdbf6ddf_8|py35hdbf6ddf_8|py36h7cdd4dd_9|py35h7cdd4dd_9|py27h3dfced4_9|py36h81de0dd_9|py36h74e8950_9|py27h81de0dd_9|py35h81de0dd_9|py37h74e8950_10|py35h74e8950_10|py27h81de0dd_10|py37h81de0dd_10|py35h81de0dd_10|py37h2f8d375_10|py36h2f8d375_10|py27h2f8d375_10|py36h2f8d375_11|py37hde5b4d6_12|py38hde5b4d6_12|py27h2b20989_0|py36h2b20989_0|py27hdbf6ddf_0|py36h2b20989_0|py27h2b20989_0|py27hdbf6ddf_0|py37h2b20989_1|py36hdbf6ddf_1|py27h2b20989_1|py36h2b20989_2|py37h2b20989_2|py27hdbf6ddf_2|py37hdbf6ddf_2|py36hdbf6ddf_2|py27hdbf6ddf_3|py36h2b20989_4|py36hdbf6ddf_4|py36h2f8d375_0|py36hde5b4d6_0|py27h2f8d375_4|py36h81de0dd_4|py38h2f8d375_4|py36h2f8d375_5|py37h2f8d375_5|py27hde5b4d6_5|py37hde5b4d6_5|py27h3dfced4_0|py35h3dfced4_0|py37h3dfced4_0|py37h74e8950_0|py36h81de0dd_0|py27h81de0dd_0|py36h2f8d375_0|py27h81de0dd_0|py36h2f8d375_0|py36h81de0dd_0|py27h2f8d375_1|py27h81de0dd_1|py36h81de0dd_1|py37h2f8d375_1|py36h2f8d375_0|py27h81de0dd_0|py36h81de0dd_0|py36h2f8d375_0|py27h2f8d375_0|py36h81de0dd_0|py27h81de0dd_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py37h2f8d375_1|py27h2f8d375_1|py37hde5b4d6_1|py36hde5b4d6_1|py27h2f8d375_0|py36h2f8d375_0|py36hde5b4d6_0|py27hde5b4d6_0|py37h2f8d375_1|py36hde5b4d6_1|py27hde5b4d6_1|py36h2f8d375_0|py27h2f8d375_0|py36hde5b4d6_0|py27h2f8d375_0|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py27h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py36hde5b4d6_0|py38h2f8d375_0|py27h2f8d375_0|py27hde5b4d6_0|py37hfa32c7d_0|py38hfa32c7d_0|py36h75fe3a5_0|py37h75fe3a5_0|py36hfa32c7d_0|py38h75fe3a5_0|py38hde5b4d6_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py27h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py27hde5b4d6_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_1|py36h2f8d375_1|py27h2f8d375_1|py37hde5b4d6_0|py37h2f8d375_0|py27hde5b4d6_1|py36h2f8d375_1|py37hde5b4d6_0|py37h2f8d375_0|py27h2f8d375_0|py37hde5b4d6_0|py37h81de0dd_0|py37h2f8d375_0|py37h81de0dd_0|py37h2f8d375_0|py27h2f8d375_0|py37h81de0dd_1|py36h2f8d375_1|py35h2f8d375_0|py35h81de0dd_0|py37h81de0dd_0|py27h2f8d375_0|py37h2f8d375_0|py37h2f8d375_0|py27h2f8d375_0|py35h2f8d375_0|py35h81de0dd_0|py37h81de0dd_0|py36h74e8950_0|py27h74e8950_0|py35h74e8950_0|py36h3dfced4_0|py35h7cdd4dd_0|py37h7cdd4dd_0|py36h7cdd4dd_0|py27h7cdd4dd_0|py36hde5b4d6_5|py27h2f8d375_5|py38hde5b4d6_4|py37h81de0dd_4|py35h81de0dd_4|py36h2f8d375_4|py27h81de0dd_4|py35h2f8d375_4|py37h2f8d375_4|py37hde5b4d6_0|py37h2f8d375_0|py35h2b20989_4|py35hdbf6ddf_4|py37hdbf6ddf_4|py37h2b20989_4|py27hdbf6ddf_4|py27h2b20989_4|py27h2b20989_3|py36hdbf6ddf_3|py37hdbf6ddf_3|py37h2b20989_3|py36h2b20989_3|py27h2b20989_2|py37hdbf6ddf_1|py27hdbf6ddf_1|py36h2b20989_1|py35hdbf6ddf_0|py36hdbf6ddf_0|py35hdbf6ddf_0|py36hdbf6ddf_0|py35h2b20989_0|py35h9be14a7_1|py27h9be14a7_1|py36h9be14a7_1|py35h0ea5e3f_1|py27h0ea5e3f_1|py36h0ea5e3f_1|py38h2f8d375_12|py36hde5b4d6_12|py27hde5b4d6_12|py36h2f8d375_12|py27h2f8d375_12|py37h2f8d375_12|py27hde5b4d6_11|py37hde5b4d6_11|py36hde5b4d6_11|py27h2f8d375_11|py37h2f8d375_11|py35h2f8d375_10|py36h81de0dd_10|py36h74e8950_10|py27h74e8950_10|py37h74e8950_9|py35h74e8950_9|py27h74e8950_9|py37h81de0dd_9|py35h3dfced4_9|py36h3dfced4_9|py37h3dfced4_9|py37h7cdd4dd_9|py27h7cdd4dd_9|py35h2b20989_8|py27h2b20989_8|py37h2b20989_8|py37hdbf6ddf_8|py36h2b20989_8|py36hdbf6ddf_7|py27hdbf6ddf_7|py27h2b20989_7|py35h2b20989_7|py36h2b20989_7|py36hdbf6ddf_7|py27hdbf6ddf_7|py37h2b20989_6|py36h2b20989_6|py27h2b20989_6']
netcdf4=1.5.4 -> numpy[version='>=1.16.5,<2.0a0'] -> numpy-base[version='1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.17.0|1.17.0|1.17.0|1.17.0',build='py36h2f8d375_4|py35h81de0dd_4|py37h2f8d375_5|py27hde5b4d6_5|py37hde5b4d6_5|py27h3dfced4_0|py35h3dfced4_0|py37h74e8950_0|py36h81de0dd_0|py35h2f8d375_0|py36h2f8d375_0|py27h81de0dd_0|py36h2f8d375_0|py36h81de0dd_0|py36h2f8d375_1|py27h81de0dd_1|py37h2f8d375_1|py36h2f8d375_0|py27h81de0dd_0|py36h81de0dd_0|py36h2f8d375_0|py27h2f8d375_0|py36h81de0dd_0|py27h81de0dd_0|py27hde5b4d6_0|py36hde5b4d6_0|py27h2f8d375_0|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py37h2f8d375_1|py37hde5b4d6_1|py36h2f8d375_0|py36hde5b4d6_0|py37hde5b4d6_0|py27hde5b4d6_0|py27h2f8d375_1|py37h2f8d375_1|py36hde5b4d6_1|py27hde5b4d6_1|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py27h2f8d375_0|py36h2f8d375_0|py36hde5b4d6_0|py36h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py36hde5b4d6_0|py36h2f8d375_0|py27h2f8d375_0|py27hde5b4d6_0|py36hde5b4d6_0|py36h2f8d375_0|py36hde5b4d6_0|py38h2f8d375_0|py27h2f8d375_0|py27hde5b4d6_0|py37hfa32c7d_0|py38hfa32c7d_0|py36h75fe3a5_0|py37h75fe3a5_0|py36hfa32c7d_0|py38h75fe3a5_0|py38hde5b4d6_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h2f8d375_0|py27h2f8d375_0|py27hde5b4d6_0|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py27h2f8d375_0|py37h2f8d375_0|py37hde5b4d6_1|py36h2f8d375_1|py27h2f8d375_0|py37h2f8d375_0|py36hde5b4d6_1|py27hde5b4d6_1|py36h2f8d375_1|py27h2f8d375_1|py37hde5b4d6_0|py37h2f8d375_0|py37hde5b4d6_0|py37h81de0dd_0|py37h2f8d375_0|py37h81de0dd_0|py37h2f8d375_0|py27h2f8d375_0|py37h81de0dd_1|py36h81de0dd_1|py27h2f8d375_1|py35h2f8d375_0|py35h81de0dd_0|py37h81de0dd_0|py27h2f8d375_0|py37h2f8d375_0|py37h2f8d375_0|py27h2f8d375_0|py35h81de0dd_0|py37h81de0dd_0|py27h81de0dd_0|py36h74e8950_0|py27h74e8950_0|py35h74e8950_0|py37h3dfced4_0|py36h3dfced4_0|py35h7cdd4dd_0|py37h7cdd4dd_0|py36h7cdd4dd_0|py27h7cdd4dd_0|py36hde5b4d6_5|py27h2f8d375_5|py36h2f8d375_5|py38hde5b4d6_4|py38h2f8d375_4|py36h81de0dd_4|py37h81de0dd_4|py27h2f8d375_4|py27h81de0dd_4|py35h2f8d375_4|py37h2f8d375_4']

Package setuptools conflicts for:
python=3.8 -> pip -> setuptools
netcdf4=1.5.4 -> setuptools

Package curl conflicts for:
pynio -> libnetcdf[version='>=4.7.4,<4.7.5.0a0'] -> curl[version='>=7.44.0,<8|>=7.59.0,<8.0a0|>=7.64.1,<8.0a0|>=7.69.1,<8.0a0|>=7.71.1,<8.0a0|>=7.55,<8|>=7.54.1,<8']
pynio -> curl

Package numpy conflicts for:
pynio -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.14|>=1.14.6,<2.0a0|>=1.7|1.9.*|>=1.11.3,<2.0a0|>=1.9.3,<2.0a0']
pynio -> gdal -> numpy[version='>=1.16.5,<2.0a0']

Package libgfortran-ng conflicts for:
pynio -> libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']
pynio -> numpy[version='>=1.14'] -> libgfortran-ng[version='>=4.9']
Note that strict channel priority may have removed packages required for satisfiability.
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /home/mathause/conda
            shell level : 1
       user config file : /home/mathause/.condarc
 populated config files : /home/mathause/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31
       base environment : /home/mathause/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mathause/conda/pkgs
                          /home/mathause/.conda/pkgs
       envs directories : /home/mathause/conda/envs
                          /home/mathause/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-48-generic linuxmint/20 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>
